import { Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<Box>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Hi hello World</h1>
			</main>

			<footer></footer>
		</Box>
	);
}
